dependencies:
  - python=3
  - pip:
    - spacy
    - ipykernel
    - scipy
    - numpy
    - scikit-learn
    - matplotlib
    - pandas
    - thinc
    - requests
    - wxpython
    - twisted
    - pygame
    
    - ipython
    - tensorflow
    - pytorch
    
    